import { asset } from '$app/paths';
import { HABITATS, SUBSTRATES } from '$lib/domain/habitat';

/**
 * Seabed textures ship as both JPEG XL and WebP at four sizes. Only Safari
 * decodes JXL without a flag today, so the format is decided once at startup by
 * actually decoding a pixel rather than by sniffing the user agent.
 *
 * Measured on this texture set, JXL at matched quality is about level with WebP
 * overall and roughly 10 percent smaller lossless. It is here because it costs
 * nothing to offer, not because it saves much.
 */

export const TEXTURE_SIZES = [256, 512, 1024, 2048] as const;
export type TextureSize = (typeof TEXTURE_SIZES)[number];

export type TextureFormat = 'jxl' | 'webp';

/** A real one-pixel lossless JXL, produced by libjxl. If it decodes, JXL is readable. */
const JXL_PROBE =
	'data:image/jxl;base64,/woAEBAJCAIBAIQCSxibnHGEAziAAzggSsA5BQEAIESACBABIkCE//fv+e+hMeeca+1zb5IkCQFVVVVVVdX///9z7+vu7u6G//fv+e+hMeeca+1zb5IkCQFVVVVVVdX///9z7+vu7u6G//fv+e+hMeeca+1zb5IkCQFVVVVVVdX///9z7+vu7u6G//fv+e+hMeeca+1zb5IkCQFVVVVVVdX///9z7+vu7u4+AAA=';

let detected: Promise<TextureFormat> | undefined;

export const textureFormat = (): Promise<TextureFormat> => {
	detected ??= (async (): Promise<TextureFormat> => {
		if (typeof createImageBitmap !== 'function') return 'webp';
		try {
			const bitmap = await createImageBitmap(await (await fetch(JXL_PROBE)).blob());
			bitmap.close();
			return 'jxl';
		} catch {
			return 'webp';
		}
	})();
	return detected;
};

/**
 * How wide one repeat of a seabed pattern lands on screen.
 *
 * A fill-pattern is laid out in CSS pixels: MapLibre divides the image by the
 * pixelRatio it was registered at. That ratio was a constant 2 while the image
 * size followed the device, so the same seabed repeated every 256 CSS pixels on
 * a laptop and every 512 on a retina screen, where it reads as blotches rather
 * than as ground. Registering each texture at `bitmap.width / PATTERN_CSS_SIZE`
 * pins the repeat wherever it is drawn, and the size below is then only a
 * question of how many device pixels to spend on it.
 */
export const PATTERN_CSS_SIZE = 256;

export const patternPixelRatio = (bitmapWidth: number): number =>
	bitmapWidth / PATTERN_CSS_SIZE;

/**
 * Which texture size to load. Enough device pixels for the screen it is drawn
 * on, capped on a phone because the whole set is decoded and held: 22 textures
 * at 1024 is 92 MB of bitmap, which is not a thing to ask of the device that
 * also has to hold the tiles offline. Printing always takes the full one.
 *
 * The floor is what makes this safe to land before every caller passes the
 * ratio above to `addImage`. A caller still registering at a fixed 2 gets
 * 512 / 2, which is the same 256 CSS pixels, on every screen up to 2x.
 */
export const sizeForScreen = (devicePixelRatio: number, coarsePointer: boolean): TextureSize => {
	const wanted = Math.max(PATTERN_CSS_SIZE * devicePixelRatio, PATTERN_CSS_SIZE * 2);
	const cap: TextureSize = coarsePointer ? 512 : 1024;
	return TEXTURE_SIZES.find((size) => size >= wanted && size <= cap) ?? cap;
};

export const textureUrl = (name: string, size: TextureSize, format: TextureFormat): string =>
	asset(`/textures/${size}/${name}.${format}`);

/**
 * The hatch the style paints over water the habitat survey never classified. It
 * is generated by the texture build rather than taken from the pack, so no real
 * class can ever be confused with it.
 */
export const UNSURVEYED_TEXTURE = 'unsurveyed';

/** Every distinct texture either catalogue references, plus the hatch, deduplicated. */
export const texturePalette = (): readonly string[] => [
	...new Set([UNSURVEYED_TEXTURE, ...[...HABITATS, ...SUBSTRATES].map((c) => c.texture)])
];

export interface LoadedTexture {
	readonly name: string;
	readonly bitmap: ImageBitmap;
	/** Hand this to `addImage`. A constant here is what made the pattern follow the screen density. */
	readonly pixelRatio: number;
}

/**
 * MapLibre's addImage wants an ImageBitmap. Fetching each texture separately
 * rather than packing a sprite sheet is deliberate: it lets the print path swap
 * in the 2048 set under the same image ids without rebuilding a sprite.
 */
export const loadTextures = async (
	names: readonly string[],
	size: TextureSize,
	signal?: AbortSignal
): Promise<readonly LoadedTexture[]> => {
	const format = await textureFormat();
	return Promise.all(
		names.map(async (name) => {
			const response = await fetch(textureUrl(name, size, format), signal ? { signal } : {});
			if (!response.ok) throw new Error(`texture ${name} at ${size}: HTTP ${response.status}`);
			const bitmap = await createImageBitmap(await response.blob());
			return { name, bitmap, pixelRatio: patternPixelRatio(bitmap.width) };
		})
	);
};
